// packages/solid/src/components/SvedaToolbar.tsx
import { History, Maximize2, MessageSquare, Minimize2, PanelRight, Sparkles, X } from 'lucide-solid';
import { type Component, Show, createMemo } from 'solid-js';
import { useSvedaT } from '../i18n/index';
import { cn } from '../lib/utils';

const iconButtonClass =
  'inline-flex h-9 w-9 items-center justify-center bg-transparent text-muted-foreground hover:text-foreground';

export interface SvedaToolbarProps {
  isMobile: boolean;
  viewMode: string;
  isImmersiveDesktop?: boolean;
  showHistorySidebar?: boolean;
  title: string;
  viewModeFloatingLabel?: string;
  viewModeFixedLabel?: string;
  immersiveEnterLabel?: string;
  immersiveExitLabel?: string;
  immersiveBrandName?: string;
  immersiveBrandLogo?: string;
  onToggleHistorySidebar?: () => void;
  onToggleViewMode?: () => void;
  onEnterImmersive?: () => void;
  onExitImmersive?: () => void;
  onMinimize: () => void;
}

export const SvedaToolbar: Component<SvedaToolbarProps> = props => {
  const t = useSvedaT();

  const headerClass = createMemo(() => {
    const base =
      'flex h-12 shrink-0 flex-row items-center justify-between border-b border-border bg-card px-3';
    if (props.viewMode === 'floating' && !props.isMobile) {
      return `${base} rounded-t-[var(--sveda-radius)]`;
    }
    return `${base} rounded-none`;
  });

  return (
    <header class={headerClass()}>
      <Show
        when={!props.isImmersiveDesktop}
        fallback={
          <div class="flex min-w-0 flex-1 items-center gap-4">
            <div class="w-[min(20rem,33vw)] min-w-0">
              <div class="flex items-center gap-2">
                <Show
                  when={props.immersiveBrandLogo}
                  fallback={<Sparkles class="size-5 shrink-0 text-primary" />}
                >
                  <img
                    src={props.immersiveBrandLogo}
                    alt={props.immersiveBrandName ?? ''}
                    class="size-7 shrink-0 rounded"
                  />
                </Show>
                <span class="truncate text-lg font-bold leading-none text-foreground">
                  {props.immersiveBrandName}
                </span>
              </div>
            </div>
            <h2 class="min-w-0 flex-1 truncate text-left font-mono text-[11px] font-normal uppercase tracking-[0.14em] text-foreground">
              {props.title}
            </h2>
          </div>
        }
      >
        <div class="flex min-w-0 flex-1 items-center gap-2">
          <button
            type="button"
            class={cn(iconButtonClass, props.showHistorySidebar ? 'bg-muted/60 text-foreground' : '')}
            aria-label={t('chatHistory')}
            title={t('chatHistory')}
            onClick={() => props.onToggleHistorySidebar?.()}
          >
            <History class="h-4 w-4" />
          </button>
          <h2 class="min-w-0 flex-1 truncate text-left font-mono text-[11px] font-normal uppercase tracking-[0.14em] text-foreground">
            {props.title}
          </h2>
        </div>
      </Show>
      <div class="flex shrink-0 items-center gap-0.5">
        <Show when={!props.isMobile && props.viewMode === 'immersive'}>
          <button
            type="button"
            class={iconButtonClass}
            aria-label={props.immersiveExitLabel ?? t('immersiveModeExit')}
            title={props.immersiveExitLabel ?? t('immersiveModeExit')}
            onClick={() => props.onExitImmersive?.()}
          >
            <Minimize2 class="h-4 w-4" />
          </button>
        </Show>
        <Show when={!props.isMobile && props.viewMode !== 'immersive'}>
          <button
            type="button"
            class={iconButtonClass}
            aria-label={props.immersiveEnterLabel ?? t('immersiveModeEnter')}
            title={props.immersiveEnterLabel ?? t('immersiveModeEnter')}
            onClick={() => props.onEnterImmersive?.()}
          >
            <Maximize2 class="h-4 w-4" />
          </button>
        </Show>
        <Show when={!props.isMobile && props.viewMode !== 'immersive'}>
          <button
            type="button"
            class={iconButtonClass}
            aria-label={
              props.viewMode === 'floating'
                ? (props.viewModeFixedLabel ?? t('viewModeFixed'))
                : (props.viewModeFloatingLabel ?? t('viewModeFloating'))
            }
            title={
              props.viewMode === 'floating'
                ? (props.viewModeFixedLabel ?? t('viewModeFixed'))
                : (props.viewModeFloatingLabel ?? t('viewModeFloating'))
            }
            onClick={() => props.onToggleViewMode?.()}
          >
            <Show when={props.viewMode === 'floating'} fallback={<MessageSquare class="h-4 w-4" />}>
              <PanelRight class="h-4 w-4" />
            </Show>
          </button>
        </Show>
        <button
          type="button"
          class={iconButtonClass}
          aria-label={t('toolbarMinimize')}
          title={t('toolbarMinimize')}
          onClick={() => props.onMinimize()}
        >
          <X class="h-4 w-4" />
        </button>
      </div>
    </header>
  );
};

// packages/react/src/components/shell/SvedaToolbar.tsx
import { History, Maximize2, MessageSquare, Minimize2, PanelRight, Sparkles, X } from 'lucide-react';
import { useSvedaT } from '../../provider';
import { cn } from '../../lib/utils';
import type { SvedaChatViewMode } from '../../hooks/useSvedaChatLayout';

const iconButtonClass =
  'inline-flex h-9 w-9 items-center justify-center bg-transparent text-muted-foreground hover:text-foreground';

export interface SvedaToolbarProps {
  title: string;
  isMobile: boolean;
  viewMode: SvedaChatViewMode;
  isImmersiveDesktop: boolean;
  showHistorySidebar: boolean;
  viewModeFloatingLabel: string;
  viewModeFixedLabel: string;
  immersiveEnterLabel: string;
  immersiveExitLabel: string;
  immersiveBrandName?: string;
  immersiveBrandLogo?: string;
  onToggleHistory: () => void;
  onEnterImmersive: () => void;
  onExitImmersive: () => void;
  onToggleViewMode: () => void;
  onMinimize: () => void;
}

export function SvedaToolbar({
  title,
  isMobile,
  viewMode,
  isImmersiveDesktop,
  showHistorySidebar,
  viewModeFloatingLabel,
  viewModeFixedLabel,
  immersiveEnterLabel,
  immersiveExitLabel,
  immersiveBrandName = '',
  immersiveBrandLogo = '',
  onToggleHistory,
  onEnterImmersive,
  onExitImmersive,
  onToggleViewMode,
  onMinimize,
}: SvedaToolbarProps) {
  const t = useSvedaT();
  const headerClass = cn(
    'flex h-12 shrink-0 flex-row items-center justify-between border-b border-border bg-card px-3',
    viewMode === 'floating' && !isMobile ? 'rounded-t-[var(--sveda-radius)]' : 'rounded-none'
  );

  return (
    <header className={headerClass}>
      {!isImmersiveDesktop ? (
        <div className="flex min-w-0 flex-1 items-center gap-2">
          <button
            type="button"
            className={cn(iconButtonClass, showHistorySidebar ? 'bg-muted/60 text-foreground' : '')}
            aria-label={t('chatHistory')}
            title={t('chatHistory')}
            onClick={onToggleHistory}
          >
            <History className="h-4 w-4" />
          </button>
          <h2 className="min-w-0 flex-1 truncate text-left font-mono text-[11px] font-normal uppercase tracking-[0.14em] text-foreground">
            {title}
          </h2>
        </div>
      ) : (
        <div className="flex min-w-0 flex-1 items-center gap-4">
          <div className="w-[min(20rem,33vw)] min-w-0">
            <div className="flex items-center gap-2">
              {immersiveBrandLogo ? (
                <img src={immersiveBrandLogo} alt={immersiveBrandName} className="size-7 shrink-0 rounded" />
              ) : (
                <Sparkles className="size-5 shrink-0 text-primary" />
              )}
              <span className="truncate text-lg font-bold leading-none text-foreground">{immersiveBrandName}</span>
            </div>
          </div>
          <h2 className="min-w-0 flex-1 truncate text-left font-mono text-[11px] font-normal uppercase tracking-[0.14em] text-foreground">
            {title}
          </h2>
        </div>
      )}
      <div className="flex shrink-0 items-center gap-0.5">
        {!isMobile && viewMode === 'immersive' ? (
          <button
            type="button"
            className={iconButtonClass}
            aria-label={immersiveExitLabel}
            title={immersiveExitLabel}
            onClick={onExitImmersive}
          >
            <Minimize2 className="h-4 w-4" />
          </button>
        ) : null}
        {!isMobile && viewMode !== 'immersive' ? (
          <button
            type="button"
            className={iconButtonClass}
            aria-label={immersiveEnterLabel}
            title={immersiveEnterLabel}
            onClick={onEnterImmersive}
          >
            <Maximize2 className="h-4 w-4" />
          </button>
        ) : null}
        {!isMobile && viewMode !== 'immersive' ? (
          <button
            type="button"
            className={iconButtonClass}
            aria-label={viewMode === 'floating' ? viewModeFixedLabel : viewModeFloatingLabel}
            title={viewMode === 'floating' ? viewModeFixedLabel : viewModeFloatingLabel}
            onClick={onToggleViewMode}
          >
            {viewMode === 'floating' ? <PanelRight className="h-4 w-4" /> : <MessageSquare className="h-4 w-4" />}
          </button>
        ) : null}
        <button
          type="button"
          className={iconButtonClass}
          aria-label={t('toolbarMinimize')}
          title={t('toolbarMinimize')}
          onClick={onMinimize}
        >
          <X className="h-4 w-4" />
        </button>
      </div>
    </header>
  );
}
